// A real name for each agent conversation, instead of whatever the user typed
// first.
//
// The panel card and the tab strip both used to label a session with the user's
// latest prompt, so two sessions opened with the same phrase were
// indistinguishable — and the label moved every time the user said something
// new. No agent CLI helps here: they all leave titling to their own client
// (Codex Desktop, the OpenCode TUI, Claude's picker), so uxnan names its own,
// once, from the first exchange.
//
// The name is generated by the session's own agent CLI on its cheapest model
// (`generate_conversation_title`), so it costs a fraction of a turn and needs no
// provider key. Everything here is best-effort: if it fails, the session simply
// keeps the label it had.

import { generateConversationTitle } from '$lib/api';

/** One attempt per session, ever — a title is not worth retrying in a loop. */
type Attempt = 'pending' | 'done';

class ConversationTitles {
  /** tabId → the generated name. */
  private titles = $state<Record<string, string>>({});
  /** tabId → whether we already tried, so a failure is not retried forever. */
  private attempts = new Map<string, Attempt>();

  /** The generated name for a session, or undefined while there is none. */
  get(tabId: string): string | undefined {
    return this.titles[tabId];
  }

  /**
   * Name `tabId` from its opening exchange, unless it already has a name or an
   * attempt is in flight.
   *
   * Callers pass whatever the hook has: the user's prompt is required, the
   * agent's reply is optional (a title from the prompt alone is still far
   * better than the prompt itself). Failures are swallowed on purpose —
   * naming must never surface an error over a session that is working fine.
   */
  async ensure(input: {
    tabId: string;
    agentId: string;
    userText: string;
    assistantText?: string | null;
    cwd: string;
  }): Promise<void> {
    const { tabId, agentId, userText, cwd } = input;
    if (!tabId || !agentId || !cwd) return;
    if (!userText.trim()) return;
    if (this.attempts.has(tabId)) return;

    this.attempts.set(tabId, 'pending');
    try {
      const title = await generateConversationTitle(
        agentId,
        userText,
        input.assistantText ?? '',
        cwd,
      );
      if (title.trim()) this.titles[tabId] = title.trim();
    } catch {
      // No credit, CLI missing, timeout — the session keeps its old label.
    } finally {
      this.attempts.set(tabId, 'done');
    }
  }

  /** Forget a closed session's name (and let a future one be generated). */
  forget(tabId: string): void {
    delete this.titles[tabId];
    this.attempts.delete(tabId);
  }

  /** Test seam: drop everything. */
  reset(): void {
    this.titles = {};
    this.attempts.clear();
  }
}

export const conversationTitles = new ConversationTitles();
