// A real name for each agent conversation, instead of whatever the user typed
// first.
//
// The panel card and the tab strip both used to label a session with the user's
// latest prompt, so two sessions opened with the same phrase were
// indistinguishable — and the label moved every time the user said something
// new. No agent CLI helps here: they all leave titling to their own client
// (Codex Desktop, the OpenCode TUI, Claude's picker), so uxnan names its own,
// once, from the first exchange.
//
// The name is generated by the session's own agent CLI on its cheapest model
// (`generate_conversation_title`), so it costs a fraction of a turn and needs no
// provider key. Everything here is best-effort: if it fails, the session simply
// keeps the label it had.

import { generateConversationTitle } from '$lib/api';

/** In flight, or finished (successfully or not). */
type Attempt = 'pending' | 'done';

/**
 * How many times a session may be named before we stop trying.
 *
 * Not one: a single transient failure — the CLI busy, a lock held by the
 * interactive session, a slow cold start — used to cost the session its name
 * *permanently*, because the first attempt marked it done forever. Not
 * unbounded either: naming spends real quota, so a session that genuinely
 * cannot be named must stop asking. Two is the cheapest number that survives a
 * blip.
 */
const MAX_ATTEMPTS = 2;

class ConversationTitles {
  /** tabId → the generated name. */
  private titles = $state<Record<string, string>>({});
  /** tabId → whether an attempt is in flight, so two never overlap. */
  private attempts = new Map<string, Attempt>();
  /** tabId → attempts spent, so a failure is retried once and then dropped. */
  private tries = new Map<string, number>();

  /** The generated name for a session, or undefined while there is none. */
  get(tabId: string): string | undefined {
    return this.titles[tabId];
  }

  /**
   * Name `tabId` from its opening exchange, unless it already has a name or an
   * attempt is in flight.
   *
   * Callers pass whatever the hook has: the user's prompt is required, the
   * agent's reply is optional (a title from the prompt alone is still far
   * better than the prompt itself). Failures are swallowed on purpose —
   * naming must never surface an error over a session that is working fine.
   */
  async ensure(input: {
    tabId: string;
    agentId: string;
    /** What the session's terminal shows — the only source every agent has. */
    transcript: string;
    cwd: string;
  }): Promise<void> {
    const { tabId, agentId, transcript, cwd } = input;
    if (!tabId || !agentId || !cwd) return;
    if (!transcript.trim()) return;
    // Never overlap an in-flight attempt, never re-name a named session, and
    // never exceed the budget.
    if (this.attempts.get(tabId) === 'pending') return;
    if (this.titles[tabId]) return;
    if ((this.tries.get(tabId) ?? 0) >= MAX_ATTEMPTS) return;

    this.attempts.set(tabId, 'pending');
    this.tries.set(tabId, (this.tries.get(tabId) ?? 0) + 1);
    try {
      const title = await generateConversationTitle(agentId, transcript, cwd);
      if (title.trim()) this.titles[tabId] = title.trim();
    } catch {
      // No credit, CLI missing, timeout — the session keeps its old label, and
      // the next `done` gets one more go. The backend logs why (`[convtitle]`).
    } finally {
      this.attempts.set(tabId, 'done');
    }
  }

  /** Forget a closed session's name (and let a future one be generated). */
  forget(tabId: string): void {
    delete this.titles[tabId];
    this.attempts.delete(tabId);
    this.tries.delete(tabId);
  }

  /** Test seam: drop everything. */
  reset(): void {
    this.titles = {};
    this.attempts.clear();
    this.tries.clear();
  }
}

export const conversationTitles = new ConversationTitles();
