// Pets — the library, the active pet, and what each pet is currently reacting to.
//
// The library has two halves that resolve identically:
//   • the bundled pet, read from `static/pets/<id>/pet.json` — uxnan's own
//     artwork, the only pet we ship;
//   • imported pets under `<app-data>/pets/`, listed by the Rust side.
// Both are parsed by `$lib/pets/manifest`, so one renderer serves either.
//
// What a pet *does* comes from the precise hook layer (`agentStatus`), whose
// four states map one-to-one onto the ecosystem's animations. In `global` mode
// the highest-priority agent state wins; in `colony` mode each reporting agent
// gets its own pet — which the ADE can do and a single-session CLI cannot.
//
// Spritesheets are fetched lazily and memoized: listing a large library stays
// cheap, and a sheet is only inlined when a pet is actually shown or previewed.

import { petsList, petsSheet, petsImport, petsDelete } from "$lib/api";
import { dedupeById, parsePet, type Pet } from "$lib/pets/manifest";
import { aggregateState, type PetState } from "$lib/pets/status";
import { agentStatus } from "./agentStatus.svelte";
import { terminals } from "./terminals.svelte";
import { app } from "./app.svelte";

/** Id of the pet bundled with the app (see `static/pets/`). */
export const BUILTIN_PET_ID = "uxni";

/** A reported state grows stale after this long; a pet stops acting on it and
 *  goes back to resting, matching how the sidebar dims a stale report. */
const STALE_MS = 30 * 60 * 1000;

/** One pet placed on screen, with the agent it is reflecting. */
export interface PetInstance {
  /** Stable key: the tab id in colony mode, `"global"` for the single pet. */
  key: string;
  state: PetState;
  /** Tab to focus when the pet is clicked; `undefined` when nothing to focus. */
  tabId?: string;
  /** Short label (the agent's task) for the tooltip. */
  label?: string;
}

class PetStore {
  /** Every pet available to select, bundled first. */
  library = $state<Pet[]>([]);
  /** Spritesheet URLs by pet id, resolved lazily. */
  private sheets = $state<Record<string, string>>({});
  /** Pet ids whose sheet is currently being fetched (dedupes concurrent asks). */
  private pending = new Set<string>();
  /** True once the library has been loaded at least once. */
  loaded = $state(false);
  /** Last load/import error, surfaced by the Settings section. */
  error = $state("");

  /** The pet the user selected, falling back to the bundled one. */
  get active(): Pet | undefined {
    const id = app.petSettings.activePetId || BUILTIN_PET_ID;
    return this.library.find((p) => p.id === id) ?? this.library[0];
  }

  /** Whether pets should render at all. */
  get enabled(): boolean {
    return app.petSettings.enabled === true;
  }

  /** The spritesheet URL for a pet, or `undefined` until it has been resolved.
   *
   *  Deliberately a **pure read**: components call it from markup, and kicking a
   *  load off from here would mutate `sheets` while a derived/template is being
   *  evaluated — which Svelte 5 rejects with `state_unsafe_mutation`, taking the
   *  whole render down with it. Loading is requested from an `$effect` instead,
   *  via [`ensureSheet`]. */
  sheet(id: string): string | undefined {
    return this.sheets[id];
  }

  /** Ask for a pet's spritesheet to be resolved. Safe to call repeatedly (it
   *  memoizes and de-dupes); call it from an `$effect`, never from markup. */
  async ensureSheet(id: string): Promise<void> {
    await this.loadSheet(id);
  }

  /** Load (and memoize) one pet's spritesheet. Bundled pets are plain static
   *  assets; imported ones are inlined by the backend as data URLs. */
  private async loadSheet(id: string): Promise<void> {
    if (this.sheets[id] !== undefined || this.pending.has(id)) return;
    const pet = this.library.find((p) => p.id === id);
    if (!pet) return;
    this.pending.add(id);
    try {
      const url =
        pet.source === "builtin"
          ? `/pets/${pet.id}/${pet.spritesheetPath}`
          : await petsSheet(id);
      await this.measureGrid(pet, url);
      this.sheets = { ...this.sheets, [id]: url };
    } catch (err) {
      // A pet whose sheet can't be read simply doesn't render; the library entry
      // stays so the user can see it and remove it from Settings.
      this.error = err instanceof Error ? err.message : String(err);
    } finally {
      this.pending.delete(id);
    }
  }

  /**
   * Derive a pack's grid from its actual spritesheet when the manifest didn't
   * declare one.
   *
   * Packs generated by `hatch-pet` routinely ship only an id and a sheet, and
   * sheets are not all the same height (v2 packs are 11 rows, not 9). Assuming
   * the conventional grid there would slice every frame at the wrong offset, so
   * the columns/rows are measured from the decoded image using the conventional
   * cell size. A pack that *did* declare its grid is left alone.
   */
  private async measureGrid(pet: Pet, url: string): Promise<void> {
    if (pet.frameExplicit || typeof Image === "undefined") return;
    try {
      const img = new Image();
      img.src = url;
      await img.decode();
      const columns = Math.max(1, Math.round(img.naturalWidth / pet.frame.width));
      const rows = Math.max(1, Math.round(img.naturalHeight / pet.frame.height));
      if (columns !== pet.frame.columns || rows !== pet.frame.rows) {
        pet.frame = { ...pet.frame, columns, rows };
      }
    } catch {
      // Undecodable here (or no DOM) — the conventional grid still renders
      // something rather than nothing.
    }
  }

  /** Load the bundled pet plus every installed one. Safe to call repeatedly —
   *  the Settings section re-runs it after an import or delete. */
  async load(): Promise<void> {
    const library: Pet[] = [];
    // Bundled pet: a static asset, so this works in the browser preview too.
    try {
      const res = await fetch(`/pets/${BUILTIN_PET_ID}/pet.json`);
      if (res.ok) {
        library.push(
          parsePet(await res.json(), BUILTIN_PET_ID, { source: "builtin" }),
        );
      }
    } catch {
      // No bundled pet available (unexpected) — imported pets still work.
    }
    try {
      for (const p of await petsList()) {
        library.push(
          parsePet(p.manifest, p.id, { source: "imported", origin: p.origin, dir: p.dir }),
        );
      }
    } catch {
      // No Tauri backend (web preview): the bundled pet is the whole library.
    }
    // One entry per id: an imported pack may share the bundled pet's id (that is
    // how you replace the mascot), and two entries with the same id break the
    // keyed `{#each}` that renders the library. Imported pets come last, so a
    // deliberate install wins.
    const merged = dedupeById(library);
    // Drop cached sheets for pets that are gone, so a re-imported pet re-reads.
    const ids = new Set(merged.map((p) => p.id));
    for (const id of Object.keys(this.sheets)) {
      if (!ids.has(id)) delete this.sheets[id];
    }
    this.library = merged;
    this.loaded = true;
  }

  /** Import a pet folder and refresh the library. */
  async import(source: string, origin: string, overwrite = false): Promise<boolean> {
    this.error = "";
    try {
      await petsImport(source, origin, overwrite);
      await this.load();
      return true;
    } catch (err) {
      this.error = err instanceof Error ? err.message : String(err);
      return false;
    }
  }

  /** Delete an installed pet, clearing the selection if it was the active one. */
  async remove(id: string): Promise<void> {
    this.error = "";
    try {
      await petsDelete(id);
      if (app.petSettings.activePetId === id) app.updatePets({ activePetId: "" });
      await this.load();
    } catch (err) {
      this.error = err instanceof Error ? err.message : String(err);
    }
  }

  /**
   * Live agent reports that are recent enough to act on, paired with their tab.
   * A stale report is ignored rather than leaving a pet stuck mid-animation on
   * something that finished half an hour ago.
   */
  private reporting(): { tabId: string; state: PetState; label?: string }[] {
    const now = Date.now();
    const out: { tabId: string; state: PetState; label?: string }[] = [];
    for (const [tabId, live] of Object.entries(agentStatus.byId)) {
      if (now - live.lastUpdate > STALE_MS) continue;
      out.push({ tabId, state: live.status, label: live.prompt ?? undefined });
    }
    return out;
  }

  /**
   * The pets to render right now.
   *
   * `global` collapses every agent into one pet (what a single-session CLI can
   * do); `colony` gives each reporting agent its own. Either way an idle app
   * still shows one resting pet, so the companion doesn't blink in and out.
   */
  get instances(): PetInstance[] {
    if (!this.enabled) return [];
    const reports = this.reporting();
    if (app.petSettings.mode === "colony" && reports.length > 0) {
      return reports.map((r) => ({
        key: r.tabId,
        state: r.state,
        tabId: r.tabId,
        label: r.label,
      }));
    }
    const state = aggregateState(reports.map((r) => r.state));
    // Focus target: the agent actually driving the shown state.
    const driver = reports.find((r) => r.state === state);
    return [{ key: "global", state, tabId: driver?.tabId, label: driver?.label }];
  }

  /** Jump to the terminal whose agent a pet is reflecting. */
  focus(tabId: string | undefined): void {
    if (!tabId) return;
    for (const { tab, workspace } of terminals.tabsWithWorkspace()) {
      if (tab.id === tabId) {
        terminals.revealTab(workspace, tabId);
        return;
      }
    }
  }
}

/** Singleton pets store shared across the app. */
export const pets = new PetStore();
