// Pet manifest parsing — the format side of the pets feature.
//
// The schema is the one the Codex CLI uses, so packs built for it (including
// the community galleries) load here unmodified:
//
//   { id, displayName, description, spritesheetPath,
//     frame: { width, height, columns, rows },
//     animations: { <name>: { frames: number[], fps, loop, fallback } } }
//
// Every field is optional. A pack that is nothing but a spritesheet still
// works: the defaults below reproduce the conventional 8x9 grid of 192x208
// frames, and `resolveAnimation` walks `fallback` chains so a state a pack
// never defined still renders something sensible.
//
// This module is pure (no Tauri, no DOM) so it is unit-testable and shared by
// the bundled pet, imported pets and the Settings preview alike. The Rust side
// validates the same shape at the trust boundary (`src-tauri/src/pets.rs`);
// this is the rendering-side reader, so it is forgiving rather than strict —
// it repairs what it can and never throws on a malformed pack.

/** The sprite grid: `columns * rows` frames of `width * height`, row-major. */
export interface PetFrameSpec {
  width: number;
  height: number;
  columns: number;
  rows: number;
}

/** One sprite shown for a while. */
export interface PetFrame {
  /** Index into the spritesheet, row-major. */
  index: number;
  /** How long this frame is held, in ms. */
  ms: number;
}

/**
 * One named animation: frames with **individual** durations, plus the point the
 * loop returns to.
 *
 * Both details are load-bearing, and both come from the reference implementation
 * rather than being invented here:
 *
 * - **Per-frame durations.** A flat frame rate makes a pet twitch. The reference
 *   idle holds its resting poses for 1.7 s and 1.9 s while passing through the
 *   in-betweens in 0.66 s — 6.6 s for one breath, where a uniform 8 fps loop over
 *   the same frames takes 0.75 s.
 * - **`loopStart`.** Frames before it play once; from there the animation repeats
 *   forever. A state animation is its row three times *followed by the idle
 *   frames*, with `loopStart` at the idle part — so the pet reacts a few times
 *   and then settles, instead of miming a state for as long as it lasts.
 */
export interface PetAnimation {
  frames: PetFrame[];
  /** Index into `frames` where the loop restarts. `frames.length` = play once. */
  loopStart: number;
  /** Animation to use instead when this one has no frames. */
  fallback: string;
}

/** A parsed, render-ready pet. */
export interface Pet {
  id: string;
  displayName: string;
  description: string;
  /** File name of the spritesheet inside the pet folder. */
  spritesheetPath: string;
  frame: PetFrameSpec;
  /** Whether the pack declared its own grid. When false, `frame` holds the
   *  conventional default and the real grid is measured from the spritesheet
   *  once it loads — packs generated by `hatch-pet` routinely omit it, and
   *  guessing wrong slices every frame at the wrong offset. */
  frameExplicit: boolean;
  /** Declared `spriteVersionNumber` (0 when the pack has none). Version 2 marks
   *  the 8x11 layout whose last two rows are the 16 look-direction poses. */
  spriteVersion: number;
  /** True once grid *and* animations are final — either declared by the pack or
   *  derived from the decoded sheet. The library is rebuilt on every reload, so
   *  the sheet loader uses this to know a fresh `Pet` still needs measuring. */
  layoutResolved: boolean;
  animations: Record<string, PetAnimation>;
  /** `builtin` ships with uxnan; `imported` was brought in by the user. */
  source: "builtin" | "imported";
  /** Where an imported pet came from, shown as attribution. Empty for builtins. */
  origin: string;
  /** Absolute folder, for "reveal in file manager". Empty for builtins. */
  dir: string;
}

/** The conventional grid, matching the ecosystem's spritesheet layout. */
export const DEFAULT_FRAME: PetFrameSpec = {
  width: 192,
  height: 208,
  columns: 8,
  rows: 9,
};

/** Frame duration used when a pack specifies neither `fps` nor a default. */
export const DEFAULT_FRAME_MS = 125; // 8 fps, the format's documented default

/**
 * Rendered pet heights offered in Settings, in px.
 *
 * These are the height of the **sprite cell**, and a generated pack fills nearly
 * all of it (the reference art leaves ~6 px of padding top and bottom), so the
 * number is close to the character's real height. The ladder is deliberately
 * generous: the reference desktop pet at its middle setting stands around 200 px,
 * and an earlier ladder topping out at 160 made every option look small beside it.
 */
export const PET_SIZES = [96, 144, 200, 260] as const;

/** Smallest / largest height accepted, whatever is persisted. */
export const PET_SIZE_MIN = 40;
export const PET_SIZE_MAX = 320;

/**
 * The ladder entry closest to `size`, so a value persisted before the ladder
 * changed still selects a sensible option instead of showing an empty picker.
 */
export function nearestPetSize(size: number | undefined): number {
  const target = size ?? PET_SIZES[1];
  return PET_SIZES.reduce((best, option) =>
    Math.abs(option - target) < Math.abs(best - target) ? option : best,
  );
}

/** The animation every fallback chain ultimately resolves to. */
export const BASE_ANIMATION = "idle";

/** Bounds mirroring the Rust validator, so a bogus grid can't blow up layout. */
const MAX_FRAME_DIM = 2048;
const MAX_GRID = 256;

function int(value: unknown, fallback: number): number {
  const n = typeof value === "number" ? value : Number(value);
  return Number.isFinite(n) && n > 0 ? Math.floor(n) : fallback;
}

function str(value: unknown): string {
  return typeof value === "string" ? value.trim() : "";
}

/** Clamp a parsed grid into the supported range, falling back per-axis. */
function parseFrame(raw: unknown): PetFrameSpec {
  const f = (raw ?? {}) as Record<string, unknown>;
  const clamp = (v: unknown, def: number, max: number) => Math.min(int(v, def), max);
  return {
    width: clamp(f.width, DEFAULT_FRAME.width, MAX_FRAME_DIM),
    height: clamp(f.height, DEFAULT_FRAME.height, MAX_FRAME_DIM),
    columns: clamp(f.columns, DEFAULT_FRAME.columns, MAX_GRID),
    rows: clamp(f.rows, DEFAULT_FRAME.rows, MAX_GRID),
  };
}

/**
 * Parse one animation entry. Frame indices outside the sheet are dropped
 * (rather than failing the pack), and a `frames` array that isn't an array at
 * all yields an empty animation, which `resolveAnimation` then falls through.
 */
function parseAnimation(raw: unknown, total: number): PetAnimation {
  const a = (raw ?? {}) as Record<string, unknown>;
  const frames = Array.isArray(a.frames)
    ? a.frames
        .map((n) => (typeof n === "number" ? Math.floor(n) : Number.NaN))
        .filter((n) => Number.isFinite(n) && n >= 0 && n < total)
    : [];
  const fps = typeof a.fps === "number" && Number.isFinite(a.fps) && a.fps > 0 ? a.fps : 0;
  const ms = fps > 0 ? Math.max(1000 / 60, 1000 / fps) : DEFAULT_FRAME_MS;
  const timed = frames.map((index) => ({ index, ms }));
  return {
    frames: timed,
    // A manifest declaring `loop: false` plays once and holds its last frame.
    loopStart: a.loop === false ? timed.length : 0,
    fallback: str(a.fallback),
  };
}

/**
 * Read a raw manifest object into a render-ready [`Pet`].
 *
 * `id` is supplied by the caller (the folder name for imported pets) and only
 * overridden by the manifest when it declares a usable one. A pack with no
 * animations at all still renders: [`resolveAnimation`] synthesizes an `idle`
 * that walks the whole sheet.
 */
export function parsePet(
  raw: unknown,
  id: string,
  opts: { source?: Pet["source"]; origin?: string; dir?: string } = {},
): Pet {
  const m = (raw ?? {}) as Record<string, unknown>;
  const frame = parseFrame(m.frame);
  const rawFrame = (m.frame ?? {}) as Record<string, unknown>;
  const positive = (v: unknown) => Number.isFinite(Number(v)) && Number(v) > 0;
  const frameExplicit = positive(rawFrame.columns) && positive(rawFrame.rows);
  // Only clip frame indices when we actually know the grid. For a pack that
  // didn't declare one, the real size arrives with the image, and clipping
  // against the assumed default would silently drop valid frames.
  const total = frameExplicit ? frame.columns * frame.rows : Number.POSITIVE_INFINITY;

  const animations: Record<string, PetAnimation> = {};
  const rawAnims = (m.animations ?? {}) as Record<string, unknown>;
  if (rawAnims && typeof rawAnims === "object") {
    for (const [name, spec] of Object.entries(rawAnims)) {
      const parsed = parseAnimation(spec, total);
      if (parsed.frames.length > 0) animations[name] = parsed;
    }
  }

  return {
    id: str(m.id) || id,
    displayName: str(m.displayName) || str(m.id) || id,
    description: str(m.description),
    spritesheetPath: str(m.spritesheetPath) || "spritesheet.webp",
    frame,
    frameExplicit,
    spriteVersion: int(m.spriteVersionNumber, 0),
    // A pack that declared both halves needs no measuring; anything else is
    // completed from the decoded sheet (see the store's `measureSheet`).
    layoutResolved: frameExplicit && Object.keys(animations).length > 0,
    animations,
    source: opts.source ?? "imported",
    origin: opts.origin ?? "",
    dir: opts.dir ?? "",
  };
}

/**
 * The animation a pet should play for `name`, following `fallback` chains and
 * ending at [`BASE_ANIMATION`]. A pet with no usable animation at all gets a
 * synthesized one that simply walks every frame, so even a bare spritesheet
 * animates instead of rendering nothing.
 *
 * Chains are followed with a visited-set, so a pack whose fallbacks point at
 * each other (`a → b → a`) resolves instead of looping forever.
 */
export function resolveAnimation(pet: Pet, name: string): PetAnimation {
  const seen = new Set<string>();
  let current = name;
  while (current && !seen.has(current)) {
    seen.add(current);
    const anim = pet.animations[current];
    if (anim && anim.frames.length > 0) return anim;
    current = anim?.fallback || (current === BASE_ANIMATION ? "" : BASE_ANIMATION);
  }
  const base = pet.animations[BASE_ANIMATION];
  if (base && base.frames.length > 0) return base;
  const total = pet.frame.columns * pet.frame.rows;
  return {
    frames: Array.from({ length: Math.max(1, total) }, (_, i) => ({
      index: i,
      ms: DEFAULT_FRAME_MS,
    })),
    loopStart: 0,
    fallback: "",
  };
}

/**
 * The idle animation's per-frame durations, in ms.
 *
 * Not a frame rate: the resting poses are held for well over a second while the
 * in-betweens pass quickly, which is what reads as breathing. One cycle is 6.6 s
 * — a uniform loop over the same frames would take under a second and look
 * frantic. Taken from the reference implementation.
 */
const IDLE_FRAME_MS = [1680, 660, 660, 840, 840, 1920];

/**
 * The conventional animation set of a generated pack.
 *
 * Packs produced by `hatch-pet` (and the community galleries built on it) ship
 * *only* an id, a description and a sheet path — no `frame`, no `animations` —
 * because the layout is the format's convention rather than per-pack data. A
 * reader without these defaults renders one endless walk over every frame,
 * sweeping rows nothing is supposed to use.
 *
 * Rows, **frame counts**, durations and aliases all mirror the reference
 * implementation. The counts matter as much as the rows: a row is not
 * necessarily full (a generated wave is 4 frames in an 8-wide grid) and playing
 * the blank remainder makes the pet flicker out of existence. They are declared
 * here rather than detected from the image, which keeps this pure — and avoids
 * reading pixels back from a canvas, which a webview may refuse outright.
 *
 * The `frameMs`/`finalFrameMs` below are the reference's **raw** numbers; what
 * actually plays is those times [`STATE_PACE`] — see that constant for why.
 *
 * Note that **`running` is row 7, not row 1**: rows 1 and 2 are `running-right` /
 * `running-left`, a run that *travels*, for a pet that walks across a desktop.
 * The busy state is row 7, animated in place — wiring it to row 1 makes the pet
 * sprint for as long as a task lasts.
 */
interface DefaultAnimationSpec {
  row: number;
  count: number;
  frameMs: number;
  finalFrameMs: number;
}

const DEFAULT_ANIMATION_SPECS: Record<string, DefaultAnimationSpec> = {
  "running-right": { row: 1, count: 8, frameMs: 120, finalFrameMs: 220 },
  "running-left": { row: 2, count: 8, frameMs: 120, finalFrameMs: 220 },
  waving: { row: 3, count: 4, frameMs: 140, finalFrameMs: 280 },
  jumping: { row: 4, count: 5, frameMs: 140, finalFrameMs: 280 },
  failed: { row: 5, count: 8, frameMs: 140, finalFrameMs: 240 },
  waiting: { row: 6, count: 6, frameMs: 150, finalFrameMs: 260 },
  running: { row: 7, count: 6, frameMs: 120, finalFrameMs: 220 },
  review: { row: 8, count: 6, frameMs: 150, finalFrameMs: 280 },
  // Aliases the format also recognises, sharing a row with the above.
  move_right: { row: 1, count: 8, frameMs: 120, finalFrameMs: 220 },
  move_left: { row: 2, count: 8, frameMs: 120, finalFrameMs: 220 },
  wave: { row: 3, count: 4, frameMs: 140, finalFrameMs: 280 },
  bounce: { row: 4, count: 5, frameMs: 140, finalFrameMs: 280 },
  sad: { row: 5, count: 8, frameMs: 140, finalFrameMs: 240 },
};

/** The animation names a generated pack is assumed to provide. */
export const DEFAULT_ANIMATION_NAMES = [BASE_ANIMATION, ...Object.keys(DEFAULT_ANIMATION_SPECS)];

/**
 * How much the conventional state rows are slowed against the reference's raw
 * timings.
 *
 * The reference's 120–150 ms a frame is tuned for a glance at a terminal.
 * Beside this pet's idle — which deliberately breathes once every 6.6 s — a raw
 * row reads as a twitch: the wave is over before the eye lands on it, which is
 * exactly what "every preview except resting moves too fast" looks like. So the
 * derived rows are stretched, and every gesture uses the *same* stretch: a wave
 * looks alike whether the pet waves because the agent needs you, because it was
 * clicked, or just to pass the time.
 *
 * The stretch is bounded on the other side too. Past roughly a quarter of a
 * second, a held frame stops reading as a pose and starts reading as a pause,
 * and the gesture turns stepped — the pet looks mechanical rather than alive.
 * 2.0 is the compromise: 240–300 ms a frame (down from the 288–360 ms of the
 * original 2.4), still unhurried next to the idle, but with the poses flowing
 * into each other instead of clicking between stills. Only the derived
 * conventional set is stretched; a pack that declares its own `fps` knows
 * better and keeps it.
 */
export const STATE_PACE = 2.0;

/** How many times a state animation plays before the pet settles into idle. */
export const STATE_REPEATS = 3;

/**
 * Build the conventional animation set for a sheet `columns` frames wide.
 *
 * Every state animation is its row repeated [`STATE_REPEATS`] times **followed by
 * the idle frames**, looping from where idle begins — so the pet reacts to a
 * state a few times and then calms down, rather than performing it for as long as
 * the state lasts. A row that would not fit in the grid is skipped.
 */
export function defaultAnimations(columns: number, rows: number): Record<string, PetAnimation> {
  const out: Record<string, PetAnimation> = {};
  const cols = Math.max(1, Math.floor(columns));

  const idleFrames: PetFrame[] =
    rows >= 1
      ? IDLE_FRAME_MS.slice(0, cols).map((ms, i) => ({ index: i, ms }))
      : [];
  if (idleFrames.length > 0) out[BASE_ANIMATION] = { frames: idleFrames, loopStart: 0, fallback: "" };

  for (const [name, spec] of Object.entries(DEFAULT_ANIMATION_SPECS)) {
    if (spec.row >= rows || spec.count > cols) continue;
    const primary: PetFrame[] = Array.from({ length: spec.count }, (_, i) => ({
      index: spec.row * cols + i,
      ms: Math.round((i === spec.count - 1 ? spec.finalFrameMs : spec.frameMs) * STATE_PACE),
    }));
    const frames: PetFrame[] = [];
    for (let i = 0; i < STATE_REPEATS; i++) frames.push(...primary.map((f) => ({ ...f })));
    const loopStart = frames.length;
    frames.push(...idleFrames.map((f) => ({ ...f })));
    out[name] = {
      frames,
      // With no idle to settle into, the state itself simply loops.
      loopStart: idleFrames.length > 0 ? loopStart : 0,
      fallback: BASE_ANIMATION,
    };
  }
  return out;
}

/**
 * Collapse a library to one pet per id, later entries winning.
 *
 * The bundled pet and an imported one can genuinely share an id — importing a
 * pack called `uxni` is exactly how you'd replace the bundled mascot — and two
 * entries with the same id are not merely redundant: they break the keyed
 * `{#each}` that renders the library (`each_key_duplicate`), taking the whole
 * Pets screen down. Imported pets are passed last so a deliberate install wins
 * over the bundled default, and the original ordering is preserved.
 */
export function dedupeById(pets: readonly Pet[]): Pet[] {
  const byId = new Map<string, Pet>();
  for (const pet of pets) byId.set(pet.id, pet);
  return [...byId.values()];
}

/** Pixel offset of `index` within the sheet, for CSS `background-position`. */
export function framePosition(frame: PetFrameSpec, index: number): { x: number; y: number } {
  const total = Math.max(1, frame.columns * frame.rows);
  const i = ((Math.floor(index) % total) + total) % total;
  return {
    x: (i % frame.columns) * frame.width,
    y: Math.floor(i / frame.columns) * frame.height,
  };
}
