// Pet manifest parsing — the format side of the pets feature.
//
// The schema is the one the Codex CLI uses, so packs built for it (including
// the community galleries) load here unmodified:
//
//   { id, displayName, description, spritesheetPath,
//     frame: { width, height, columns, rows },
//     animations: { <name>: { frames: number[], fps, loop, fallback } } }
//
// Every field is optional. A pack that is nothing but a spritesheet still
// works: the defaults below reproduce the conventional 8x9 grid of 192x208
// frames, and `resolveAnimation` walks `fallback` chains so a state a pack
// never defined still renders something sensible.
//
// This module is pure (no Tauri, no DOM) so it is unit-testable and shared by
// the bundled pet, imported pets and the Settings preview alike. The Rust side
// validates the same shape at the trust boundary (`src-tauri/src/pets.rs`);
// this is the rendering-side reader, so it is forgiving rather than strict —
// it repairs what it can and never throws on a malformed pack.

/** The sprite grid: `columns * rows` frames of `width * height`, row-major. */
export interface PetFrameSpec {
  width: number;
  height: number;
  columns: number;
  rows: number;
}

/** One named animation. */
export interface PetAnimation {
  frames: number[];
  fps: number;
  loop: boolean;
  /** Animation to use instead when this one has no frames. */
  fallback: string;
}

/** A parsed, render-ready pet. */
export interface Pet {
  id: string;
  displayName: string;
  description: string;
  /** File name of the spritesheet inside the pet folder. */
  spritesheetPath: string;
  frame: PetFrameSpec;
  /** Whether the pack declared its own grid. When false, `frame` holds the
   *  conventional default and the real grid is measured from the spritesheet
   *  once it loads — packs generated by `hatch-pet` routinely omit it, and
   *  guessing wrong slices every frame at the wrong offset. */
  frameExplicit: boolean;
  animations: Record<string, PetAnimation>;
  /** `builtin` ships with uxnan; `imported` was brought in by the user. */
  source: "builtin" | "imported";
  /** Where an imported pet came from, shown as attribution. Empty for builtins. */
  origin: string;
  /** Absolute folder, for "reveal in file manager". Empty for builtins. */
  dir: string;
}

/** The conventional grid, matching the ecosystem's spritesheet layout. */
export const DEFAULT_FRAME: PetFrameSpec = {
  width: 192,
  height: 208,
  columns: 8,
  rows: 9,
};

/** Frame rate used when a pack doesn't specify one. */
export const DEFAULT_FPS = 8;

/** The animation every fallback chain ultimately resolves to. */
export const BASE_ANIMATION = "idle";

/** Bounds mirroring the Rust validator, so a bogus grid can't blow up layout. */
const MAX_FRAME_DIM = 2048;
const MAX_GRID = 256;

function int(value: unknown, fallback: number): number {
  const n = typeof value === "number" ? value : Number(value);
  return Number.isFinite(n) && n > 0 ? Math.floor(n) : fallback;
}

function str(value: unknown): string {
  return typeof value === "string" ? value.trim() : "";
}

/** Clamp a parsed grid into the supported range, falling back per-axis. */
function parseFrame(raw: unknown): PetFrameSpec {
  const f = (raw ?? {}) as Record<string, unknown>;
  const clamp = (v: unknown, def: number, max: number) => Math.min(int(v, def), max);
  return {
    width: clamp(f.width, DEFAULT_FRAME.width, MAX_FRAME_DIM),
    height: clamp(f.height, DEFAULT_FRAME.height, MAX_FRAME_DIM),
    columns: clamp(f.columns, DEFAULT_FRAME.columns, MAX_GRID),
    rows: clamp(f.rows, DEFAULT_FRAME.rows, MAX_GRID),
  };
}

/**
 * Parse one animation entry. Frame indices outside the sheet are dropped
 * (rather than failing the pack), and a `frames` array that isn't an array at
 * all yields an empty animation, which `resolveAnimation` then falls through.
 */
function parseAnimation(raw: unknown, total: number): PetAnimation {
  const a = (raw ?? {}) as Record<string, unknown>;
  const frames = Array.isArray(a.frames)
    ? a.frames
        .map((n) => (typeof n === "number" ? Math.floor(n) : Number.NaN))
        .filter((n) => Number.isFinite(n) && n >= 0 && n < total)
    : [];
  const fps = typeof a.fps === "number" && Number.isFinite(a.fps) && a.fps > 0 ? a.fps : DEFAULT_FPS;
  return {
    frames,
    fps: Math.min(fps, 60),
    loop: a.loop !== false,
    fallback: str(a.fallback),
  };
}

/**
 * Read a raw manifest object into a render-ready [`Pet`].
 *
 * `id` is supplied by the caller (the folder name for imported pets) and only
 * overridden by the manifest when it declares a usable one. A pack with no
 * animations at all still renders: [`resolveAnimation`] synthesizes an `idle`
 * that walks the whole sheet.
 */
export function parsePet(
  raw: unknown,
  id: string,
  opts: { source?: Pet["source"]; origin?: string; dir?: string } = {},
): Pet {
  const m = (raw ?? {}) as Record<string, unknown>;
  const frame = parseFrame(m.frame);
  const rawFrame = (m.frame ?? {}) as Record<string, unknown>;
  const positive = (v: unknown) => Number.isFinite(Number(v)) && Number(v) > 0;
  const frameExplicit = positive(rawFrame.columns) && positive(rawFrame.rows);
  // Only clip frame indices when we actually know the grid. For a pack that
  // didn't declare one, the real size arrives with the image, and clipping
  // against the assumed default would silently drop valid frames.
  const total = frameExplicit ? frame.columns * frame.rows : Number.POSITIVE_INFINITY;

  const animations: Record<string, PetAnimation> = {};
  const rawAnims = (m.animations ?? {}) as Record<string, unknown>;
  if (rawAnims && typeof rawAnims === "object") {
    for (const [name, spec] of Object.entries(rawAnims)) {
      const parsed = parseAnimation(spec, total);
      if (parsed.frames.length > 0) animations[name] = parsed;
    }
  }

  return {
    id: str(m.id) || id,
    displayName: str(m.displayName) || str(m.id) || id,
    description: str(m.description),
    spritesheetPath: str(m.spritesheetPath) || "spritesheet.webp",
    frame,
    frameExplicit,
    animations,
    source: opts.source ?? "imported",
    origin: opts.origin ?? "",
    dir: opts.dir ?? "",
  };
}

/**
 * The animation a pet should play for `name`, following `fallback` chains and
 * ending at [`BASE_ANIMATION`]. A pet with no usable animation at all gets a
 * synthesized one that simply walks every frame, so even a bare spritesheet
 * animates instead of rendering nothing.
 *
 * Chains are followed with a visited-set, so a pack whose fallbacks point at
 * each other (`a → b → a`) resolves instead of looping forever.
 */
export function resolveAnimation(pet: Pet, name: string): PetAnimation {
  const seen = new Set<string>();
  let current = name;
  while (current && !seen.has(current)) {
    seen.add(current);
    const anim = pet.animations[current];
    if (anim && anim.frames.length > 0) return anim;
    current = anim?.fallback || (current === BASE_ANIMATION ? "" : BASE_ANIMATION);
  }
  const base = pet.animations[BASE_ANIMATION];
  if (base && base.frames.length > 0) return base;
  const total = pet.frame.columns * pet.frame.rows;
  return {
    frames: Array.from({ length: Math.max(1, total) }, (_, i) => i),
    fps: DEFAULT_FPS,
    loop: true,
    fallback: "",
  };
}

/**
 * Collapse a library to one pet per id, later entries winning.
 *
 * The bundled pet and an imported one can genuinely share an id — importing a
 * pack called `uxni` is exactly how you'd replace the bundled mascot — and two
 * entries with the same id are not merely redundant: they break the keyed
 * `{#each}` that renders the library (`each_key_duplicate`), taking the whole
 * Pets screen down. Imported pets are passed last so a deliberate install wins
 * over the bundled default, and the original ordering is preserved.
 */
export function dedupeById(pets: readonly Pet[]): Pet[] {
  const byId = new Map<string, Pet>();
  for (const pet of pets) byId.set(pet.id, pet);
  return [...byId.values()];
}

/** Pixel offset of `index` within the sheet, for CSS `background-position`. */
export function framePosition(frame: PetFrameSpec, index: number): { x: number; y: number } {
  const total = Math.max(1, frame.columns * frame.rows);
  const i = ((Math.floor(index) % total) + total) % total;
  return {
    x: (i % frame.columns) * frame.width,
    y: Math.floor(i / frame.columns) * frame.height,
  };
}
