<script lang="ts">
  // "Pair a phone": the QR the phone scans, drawn from the RUNNING bridge's own
  // payload (`bridge_pairing_qr` → `bridge/generatePairingQr`: its LAN hosts,
  // its session, the pairing window armed) — exactly what `uxnan-bridge start`
  // prints, so a scan pairs straight away. The payload expires; the dialog
  // counts down and offers a fresh one.
  import { invoke } from "@tauri-apps/api/core";
  import * as Dialog from "$lib/components/ui/dialog";
  import { Button } from "$lib/components/ui/button";
  import { Spinner } from "$lib/components/ui/spinner";
  import { Icon } from "$lib/components/ui/icon";
  import RotateCcwIcon from "@hugeicons/core-free-icons/Rotate01Icon";
  import { i18n } from "$lib/i18n";
  import { cn } from "$lib/utils";
  import { text } from "$lib/design";

  let { open = $bindable(false) }: { open?: boolean } = $props();

  let svg = $state<string | null>(null);
  let expiresAt = $state(0);
  let now = $state(Date.now());
  let loading = $state(false);
  let error = $state<string | null>(null);

  const remaining = $derived(Math.max(0, Math.round((expiresAt - now) / 1000)));
  const expired = $derived(svg !== null && remaining === 0);

  async function load() {
    loading = true;
    error = null;
    try {
      const qr = await invoke<{ svg: string; expiresAt: number }>("bridge_pairing_qr");
      svg = qr.svg;
      expiresAt = qr.expiresAt;
      now = Date.now();
    } catch (err) {
      svg = null;
      error = err && typeof err === "object" && "message" in err ? String(err.message) : String(err);
    } finally {
      loading = false;
    }
  }

  $effect(() => {
    if (!open) return;
    void load();
    const timer = setInterval(() => (now = Date.now()), 1000);
    return () => clearInterval(timer);
  });
</script>

<Dialog.Root bind:open>
  <Dialog.Content size="small">
    <Dialog.Header>
      <Dialog.Title class={text.title}>{i18n.t("bridge.pairTitle")}</Dialog.Title>
      <Dialog.Description class={text.body}>{i18n.t("bridge.pairDesc")}</Dialog.Description>
    </Dialog.Header>

    <Dialog.Body class="flex flex-col items-center gap-3 py-0">
      <div
        class={cn(
          "flex size-56 items-center justify-center rounded-lg bg-white p-2 ring-1 ring-border/60",
          expired && "opacity-30",
        )}
      >
        {#if loading && !svg}
          <Spinner aria-label={i18n.t("common.loading")} />
        {:else if svg}
          <!-- Generated by the backend's QR encoder from the bridge's payload:
               paths and rectangles only, no text from outside. -->
          <div class="size-full [&>svg]:size-full" role="img" aria-label={i18n.t("bridge.pairQrLabel")}>
            {@html svg}
          </div>
        {/if}
      </div>

      <p class={cn(text.meta, "min-h-4 text-center")}>
        {#if error}
          <span class="text-destructive">{error}</span>
        {:else if expired}
          {i18n.t("bridge.pairExpired")}
        {:else if svg}
          {i18n.t("bridge.pairExpires", { seconds: String(remaining) })}
        {/if}
      </p>
    </Dialog.Body>

    <Dialog.Footer>
      <Button variant="ghost" onclick={() => (open = false)}>{i18n.t("common.close")}</Button>
      <Button variant="outline" disabled={loading} onclick={() => void load()}>
        <Icon icon={RotateCcwIcon} data-icon="inline-start" />
        {i18n.t("bridge.pairRegenerate")}
      </Button>
    </Dialog.Footer>
  </Dialog.Content>
</Dialog.Root>
